#include <iostream>
#include <string>
#include <cstdlib>
#include <cstring>

#include "integration_runner.hpp"

static void usage(const char* prog) {
    std::cout
        << "Usage: " << prog << " --image <path> --ground-truth <m> [OPTIONS]\n\n"
        << "  --image          <path>   Input image (generated by tools.generator)\n"
        << "  --ground-truth   <m>      True distance from Earth center, meters\n"
        << "  --focal-length   <m>      Camera focal length  (default: 85e-3)\n"
        << "  --pixel-size     <m>      Camera pixel size    (default: 20e-6)\n"
        << "  --output         <path>   Output JSON          (default: result.json)\n";
}

int main(int argc, char* argv[]) {
    std::string image_path;
    std::string output_path    = "result.json";
    double      focal_length   = 85e-3;
    double      pixel_size     = 20e-6;
    double      ground_truth_m = 0.0;

    for (int i = 1; i < argc; ++i) {
        if      (!std::strcmp(argv[i], "--image")        && i+1 < argc) image_path     = argv[++i];
        else if (!std::strcmp(argv[i], "--output")       && i+1 < argc) output_path    = argv[++i];
        else if (!std::strcmp(argv[i], "--focal-length") && i+1 < argc) focal_length   = std::stod(argv[++i]);
        else if (!std::strcmp(argv[i], "--pixel-size")   && i+1 < argc) pixel_size     = std::stod(argv[++i]);
        else if (!std::strcmp(argv[i], "--ground-truth") && i+1 < argc) ground_truth_m = std::stod(argv[++i]);
        else if (!std::strcmp(argv[i], "--help")) { usage(argv[0]); return 0; }
        else { std::cerr << "Unknown flag: " << argv[i] << "\n"; usage(argv[0]); return 1; }
    }

    if (image_path.empty() || ground_truth_m == 0.0) {
        std::cerr << "--image and --ground-truth are required\n\n";
        usage(argv[0]);
        return 1;
    }

    integration::CameraConfig camera { focal_length, pixel_size };

    auto result = integration::run_pipeline(image_path, camera, ground_truth_m);
    integration::print_result(result);
    integration::write_result_json(result, output_path);

    return result.success ? 0 : 1;
}